[package]
name = "macviz"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
clap = "4.5.40"
xml-rs = "0.8.26"
indexmap = "2.10.0"
comfy-table = "7.1.4"